# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "output_type", # <get_plot_nowcasts>
  "target_date", # <get_plot_nowcasts>
  "value", # <get_plot_nowcasts>
  "clade", # <get_plot_nowcasts>
  "output_type_id_clade", # <get_plot_nowcasts>
  "model_id", # <get_plot_nowcasts>
  "location", # <get_plot_nowcasts>
  "location", # <get_plot_mult_locs>
  "sequences", # <get_plot_mult_locs>
  "clades_modeled", # <get_plot_mult_locs>
  "seq_clade", # <get_plot_mult_locs>
  "n_seq", # <get_plot_mult_locs>
  "obs_freq", # <get_plot_mult_locs>
  "nowcast_date", # <get_plot_scores_t>
  "location", # <get_plot_scores_t>
  "target_date", # <get_plot_scores_t>
  "model_id", # <get_plot_scores_t>
  "scored", # <get_plot_scores_t>
  "model", # <get_plot_rel_skill_overall>
  "clade", # <get_clean_variant_data>
  "target_date", # <get_clean_variant_data>
  "location", # <get_clean_variant_data>
  "abbreviation", # <get_clean_variant_data>
  "location", # <extract_nowcasts>
  "nowcast_date", # <extract_nowcasts>
  "location", # <get_oracle_output>
  "location", # <get_target_data>
  NULL
))
