# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "clade", # <get_clean_variant_data>
  "location", # <get_clean_variant_data>
  "abbreviation", # <get_clean_variant_data>
  "location", # <extract_nowcasts>
  "nowcast_date", # <extract_nowcasts>
  "location", # <get_oracle_output>
  "location", # <get_target_data>
  NULL
))
